### ISSUE TITLE
Screen turns gray when adjusting position on certain datasets

### ISSUE THREAD

**Issue by PolarBean** [Tevemadar/WebAlign#1]
for some reason the main alignment window where the image is displayed turns gray when adjusting the position of the plane. I have sent @Tevemadar an example of a dataset that causes this issue. Replicated on both Chrome and Firefox

Edit: On second thought it appears any change at all makes it gray. including moving the cursor around quickly on the image.

**Comment by PolarBean** [comment]
Cant replicate on windows. must be linux specific

**Comment by Tevemadar** [comment]
Fixed in https://github.com/Tevemadar/WebAlign/commit/47d9df5e61f917536ebe853f7747c486e3acf915

**Comment by Tevemadar** [comment]
Further improved in https://github.com/Tevemadar/WebAlign/commit/463024fadb68cdf4e26e37e48d60f0f97fc679f4
